### ISSUE TITLE
Broken on `darwin` due to unsupported `glibc` package

### ISSUE THREAD

**Issue by qjcg** [usertam/context-minimals#1]
Hi! First of all, thanks for creating and sharing this excellent project!

I noticed that, despite `darwin` system support being [set in this project's flake.nix](https://github.com/usertam/context-minimals/blob/master/flake.nix#L18), I'm not able to get this to run on my `x86_64-darwin` system.

```
$ nix shell github:usertam/context-minimals#default 
error: Package ‘glibc-2.35-163’ in /nix/store/shys6pj4v8b7a1nmgmarimb0ly5a0zwq-source/pkgs/development/librarie
s/glibc/default.nix:161 is not supported on ‘x86_64-darwin’, refusing to evaluate.
```

Attempting to build with the allow unsupported system flag set fails as well:

```
$ NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1 nix shell github:usertam/context-minimals#default --impure
error: builder for '/nix/store/d66h55ygr9rixn7dh0nyj30z883908i9-glibc-2.35-163.drv' failed with exit code 1;
       last 10 log lines:
       > mips nios2 or1k powerpc riscv s390 sh checking for grep that handles long lines and -e... (cached) /nix/store/r935503nwnpzqncsf00m4zkdqvnkjxza-gnugrep-3.7/bin/grep
       > checking for egrep... (cached) /nix/store/r935503nwnpzqncsf00m4zkdqvnkjxza-gnugrep-3.7/bin/grep -E
       > sparc x86_64 checking whether gcc compiles in -mx32 mode by default... no
       >
       > configure: error:
       > *** The GNU C library is currently unavailable for this platform.
       > *** If you are interested in seeing glibc on this platform visit
       > *** the "How to submit a new port" in the wiki:
       > ***   https://sourceware.org/glibc/wiki/#Development
       > *** and join the community!
       For full logs, run 'nix log /nix/store/d66h55ygr9rixn7dh0nyj30z883908i9-glibc-2.35-163.drv'.
error: 1 dependencies of derivation '/nix/store/yd3nkzc2nh27japj0szvsd772jyxxf9i-context-minimals-2022.08.25-19-18.drv' failed to build
```

**Comment by usertam** [comment]
Hello! Thanks for dropping by the issue page and the love for the project!

Yes, this is a massive oversight on my part for not doing enough testing. Naive of me to just assume that `glibc` would work "as is" on darwin platforms. Hell, even if `glibc` worked, `patchelf` would refuse to patch the binaries... because they are not ELFs. Something like [this](https://github.com/LumiGuide/nixpkgs/blob/33c23a83bf22abd717a22eed5ae6a5b977acf802/pkgs/development/libraries/libtensorflow/default.nix#L21) is needed instead.

I am not familiar with darwin platforms and (currently) don't have the hardware to test so this will probably take some time to fix and test... :,) But I am absolutely not giving up on this!! That said, please let me know if you have new insights, and feel free to open a PR if you want to propose a fix. :D

**Comment by qjcg** [comment]
Really appreciate the feedback @usertam, thank you!

**Comment by usertam** [comment]
I did some work over at the `fix-darwin` branch and abandoned the whole `patchelf` thing on darwin but I think it should at least build now. But I'm not sure if there are hidden dragons behind the seemingly working code. Do you mind testing? :D
If so please try `nix run` or `nix shell` on `github:usertam/context-minimals/fix-darwin`. Thanks!!

**Comment by qjcg** [comment]
I've done some preliminary testing and am able to generate PDFs from ConTeXt source files just fine (e.g. via `nix run`). This is awesome! Thanks so much for resolving this issue so quickly.

**Comment by usertam** [comment]
Awesome!! I will merge to master and mark this closed then. Thanks again!
